name: BukkitExpanse
main: de.lostco.bukkitexpanse.BukkitExpanse
version: 0.1a
load: startup
commands:
   BukkitExpanse:
      description: Expand your borders.
      usage: /<command>
   expand:
      description: Pay to expand the world border
      usage: /command [additional radius] {time}
      permission: bukkitexpanse.expand
   expandprice:
      description: Check the price to expand the world border
      usage: /command [additional radius] {time}
      permission: bukkitexpanse.expandprice